# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: philosopher

env_files:
  github_token: /home/prvst/bin/github_token

before:
  hooks:
    #- ginkgo -r

builds:
- env:
  - CGO_ENABLED=0

  ldflags:
    - -w -s -X main.version=v{{ .Version }} -X main.build={{ .Timestamp }}

  goos:
    - windows
    - linux

  goarch:
    - amd64

archives:
- name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  format: zip

  files:
    - License
    - Changelog
    - philosopher.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

    vendor: University of Michigan, Department of Pathology, Proteome Bioinformatics Laboratory

    homepage: https://philosopher.nesvilab.org

    maintainer: Felipe da Veiga Leprevost <felipevl@umich.edu>

    description: A complete toolkit for shotgun proteomics data analysis.

    license: GPL-3.0

    bindir: "/usr/local/bin"

    formats:
      - deb
      - rpm

release:

  github:

    owner: Nesvilab
    name: philosopher

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  #name_template: "{{.ProjectName}} {{.Version}}"
  name_template: "Philosopher {{ .Version }}"


    #dockers:
    #  - image_templates:
    #    - "prvst/philosopher:{{ .Version }}"
    #    - "prvst/philosopher:latest"

    #    goos: linux

    #    goarch: amd64

    #    goarm: ''

    #    binaries:
    #    - philosopher
    
    #    dockerfile: Dockerfile

    # Skips the docker push. Could be useful if you also do draft releases.
    # If set to auto, the release will not be pushed to the docker repository
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Defaults to false.
    #    skip_push: true