# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: philosopher

before:
  hooks:
    #- ginkgo -r

builds:
- env:
  - CGO_ENABLED=0

  ldflags:
    - -w -s -X main.Version=${VERSION} -X main.Build=${BUILD}

  goos:
    - freebsd
    - windows
    - linux
    - darwin

  goarch:
    - amd64
    - arm64

  goarm:
    - 6
    - 7    

archives:

- format: zip

- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: x86_64



  files:
    - License
    - README.md
    - Changelog

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

#sign:
#  artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
-
  #id: "default"

  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  builds:

  replacements:
    amd64: 64-bit
    darwin: macOS

  vendor: University of Michigan, Department of Pathology, Proteome Bioinformatics Laboratory

  homepage: https://philosopher.nesvilab.org

  maintainer: Felipe da Veiga Leprevost <felipevl@umich.edu>

  description: A complete toolkit for shotgun proteomics data analysis.

  license: GPL-3.0

  bindir: "/usr/local/bin"

  formats:
    - deb
    - rpm

release:

  github:

    owner: Nesvilab
    name: philosopher

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.ProjectName}}-v{{.Version}}"

# snapcraft:
#   # You can change the name of the package.
#   # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
#   name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

#   # Replacements for GOOS and GOARCH in the package name.
#   # Keys should be valid GOOSs or GOARCHs.
#   # Values are the respective replacements.
#   # Default is empty.
#   replacements:
#     amd64: 64-bit
#     darwin: macOS

#   # The name of the snap. This is optional.
#   # Default is project name.
#   #name: drumroll

#   # Wether to publish the snap to the snapcraft store.
#   # Remember you need to `snapcraft login` first.
#   # Defaults to false.
#   publish: false

#   # Single-line elevator pitch for your amazing snap.
#   # 79 char long at most.
#   summary: A complete toolkit for shotgun proteomics data analysis.

#   # This the description of your snap. You have a paragraph or two to tell the
#   # most important story about your snap. Keep it under 100 words though,
#   # we live in tweetspace and your description wants to look good in the snap
#   # store.
#   description: |
#     Philosopher is a software designed for proteome bioinformatics analysis.

#   # A guardrail to prevent you from releasing a snap to all your users before
#   # it is ready.
#   # `devel` will let you release only to the `edge` and `beta` channels in the
#   # store. `stable` will let you release also to the `candidate` and `stable`
#   # channels. More info about channels here:
#   # https://snapcraft.io/docs/reference/channels
#   grade: stable

#   # Snaps can be setup to follow three different confinement policies:
#   # `strict`, `devmode` and `classic`. A strict confinement where the snap
#   # can only read and write in its own namespace is recommended. Extra
#   # permissions for strict snaps can be declared as `plugs` for the app, which
#   # are explained later. More info about confinement here:
#   # https://snapcraft.io/docs/reference/confinement
#   confinement: strict
  
#   # Your app's license, based on SPDX license expressions: https://spdx.org/licenses
#   # Default is empty.
#   license: GPL-3.0
  
#   # A snap of type base to be used as the execution environment for this snap.
#   # Valid values are:
#   # * bare - Empty base snap;
#   # * core - Ubuntu Core 16;
#   # * core18 - Ubuntu Core 18.
#   # Default is empty.
#   base: core18

#   # Each binary built by GoReleaser is an app inside the snap. In this section
#   # you can declare extra details for those binaries. It is optional.
#   apps:

#     # The name of the app must be the same name as the binary built or the snapcraft name.
#     philosopher:

#       # If your app requires extra permissions to work outside of its default
#       # confined space, declare them here.
#       # You can read the documentation about the available plugs and the
#       # things they allow:
#       # https://snapcraft.io/docs/reference/interfaces.
#       plugs: ["home", "network", "personal-files"]

#       # If you want your app to be autostarted and to always run in the
#       # background, you can make it a simple daemon.
#       daemon: simple

#       # If you any to pass args to your binary, you can add them with the
#       # args option.
#      #args: --foo

#   # Allows plugs to be configured. Plugs like system-files and personal-files
#   # require this.
#   # Default is empty.
#   # plugs:
#   #   personal-files:
#   #     read:
#   #     - $HOME/.foo
#   #     write:
#   #     - $HOME/.foo
#   #     - $HOME/.foobar