# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/prvst/philosopher
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: make deps

      - run: make deploy

      - run: wget -P /go/src/github.com/prvst/philosopher/test/wrksp https://github.com/Nesvilab/philosopher/releases/download/Test-data/01_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML
      - run: wget -P /go/src/github.com/prvst/philosopher/test/wrksp https://github.com/Nesvilab/philosopher/releases/download/Test-data/02_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML
      - run: wget -P /go/src/github.com/prvst/philosopher/test/wrksp https://github.com/Nesvilab/philosopher/releases/download/Test-data/03_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML

      - run: make test

      - run: make linux
