# Golang CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-go/ for more details

version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13.1

    working_directory: /go/src/github.com/nesvilab/philosopher
    steps:
      - checkout

      - run: go get -u github.com/onsi/ginkgo

      - run: go get -u github.com/onsi/gomega

      - run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - run: make deploy

      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/01_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML
      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1906_293T_proteinID_01A_QE3_122212.mzML
      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1922_293T_proteinID_02A_QE3_122212.mzML
      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1923_293T_proteinID_03A_QE3_122212.mzML
      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.pep.xml
      - run: wget -P /go/src/philosopher/test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.prot.xml

      - run: make test

      - run: make linux
