name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -u ./...

    - name: Build dependencies
      run: go build ./...
      
    - name: Deploy artifacts
      run: make deploy

    - name: Download 01_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/01_CPTAC_TMTS1-NCI7_Z_JHUZ_20170502_LUMOS.mzML

    - name: Download b1906_293T_proteinID_01A_QE3_122212.mzML
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1906_293T_proteinID_01A_QE3_122212.mzML

    - name: Download b1922_293T_proteinID_02A_QE3_122212.mzML
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1922_293T_proteinID_02A_QE3_122212.mzML
    
    - name: Download b1923_293T_proteinID_03A_QE3_122212.mzML
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/b1923_293T_proteinID_03A_QE3_122212.mzML
       
    - name: Download interact.pep.xml
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.pep.xml
    
    - name: Download interact.prot.xml
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.prot.xml
    
    - name: Run Test
      run: go test ./...
    
    - name: Build
      run: make linux
