name: philosopher-build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v1
      with:
        go-version: 1.19.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download
      
    - name: Deploy artifacts
      run: |
        unzip -o lib/dat/bindata.go.zip -d lib/dat/
        unzip -o lib/ext/cdhit/unix/bindata.go.zip -d lib/ext/cdhit/unix/
        unzip -o lib/ext/cdhit/win/bindata.go.zip -d lib/ext/cdhit/win/
        unzip -o lib/ext/comet/unix/bindata.go.zip -d lib/ext/comet/unix/
        unzip -o lib/ext/comet/win/bindata.go.zip -d lib/ext/comet/win/    
        unzip -o lib/ext/interprophet/unix/bindata.go.zip -d lib/ext/interprophet/unix/
        unzip -o lib/ext/interprophet/win/bindata.go.zip -d lib/ext/interprophet/win/
        unzip -o lib/ext/peptideprophet/unix/bindata.go.zip -d lib/ext/peptideprophet/unix/
        unzip -o lib/ext/peptideprophet/win/bindata.go.zip -d lib/ext/peptideprophet/win/
        unzip -o lib/ext/ptmprophet/unix/bindata.go.zip -d lib/ext/ptmprophet/unix/
        unzip -o lib/ext/ptmprophet/win/bindata.go.zip -d lib/ext/ptmprophet/win/
        unzip -o lib/ext/proteinprophet/unix/bindata.go.zip -d lib/ext/proteinprophet/unix/
        unzip -o lib/ext/proteinprophet/win/bindata.go.zip -d lib/ext/proteinprophet/win/
        unzip -o lib/pip/bindata.go.zip -d lib/pip/
        unzip -o lib/dat/bindata.go.zip -d lib/dat/
        unzip -o lib/obo/unimod/bindata.go.zip -d lib/obo/unimod/

    - name: Download z04397_tc-o238g-setB_MS3.mzML
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/z04397_tc-o238g-setB_MS3.mzML
       
    - name: Download interact.pep.xml
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.pep.xml
    
    - name: Download interact.prot.xml
      run: wget -P test/wrksp https://github.com/prvst/philosopher-test/releases/download/0.0.1/interact.prot.xml
    
    - name: Run Test
      run: go test ./...
    
    - name: Build
      run: go build -o philosopher main.go
